name: License Check

on: [push, pull_request]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          
      - name: Install and run Licensee
        run: |
          sudo apt-get update
          sudo apt-get install ruby-full build-essential -y
          sudo gem install licensee

          echo"export PATH=(ruby -e'print Gem.user_dir')/bin:$PATH">> $GITHUB_ENV
          echo" Ruby version: $(ruby -v)"
          echo" Licensee installed at: $(which licensee || echo 'not found')"

      - name: Run Licensee check
        run: |
          export PATH=$(ruby -e 'print Gem.user_dir')/bin:$PATH
          licensee detect. --json
          



